# This is a basic workflow to help you get started with Actions

name: Build and Deploy React App via FTP

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-deploy"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        lfs: true
        fetch-depth: 0

    # Runs a single command using the runners shell
    - name: Run react build script
      run: yarn && yarn build
      env:
        CI: false

    # Runs a set of commands using the runners shell
    - name: FTP Deployer
      uses: sand4rt/ftp-deployer@v1.3
      with:
        sftp: false
        host: hide.cs.mtu.edu
        port: 21
        username: hidecs@hide.cs.mtu.edu
        password: ${{ secrets.FTP_PASSWORD }}
        local_folder: build/
        cleanup: false
        pasive: false
